apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-secret
    namespace: instant-crud
    labels:
        app: postgres
data:
    POSTGRES_DB: "postgres"
    POSTGRES_USER: "localuser"
    POSTGRES_PASSWORD: "localpassword"