---
apiVersion: v1
kind: Service
metadata:
    name: postgres-node-port
    labels:
        app.kubernetes.io/name: postgresql-service
spec:
    type: NodePort
    selector:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: postgresql
    ports:
        - port: 5432
          targetPort: 5432
          nodePort: 31032