apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-volume
    namespace: instant-crud
    labels:
        type: local
        app: postgres
spec:
    storageClassName: manual
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /data/postgresql