apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: instant-crud
    labels:
        app: postgres
spec:
    type: NodePort
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
          nodePort: 30000
    selector:
        app: postgres